make:
	g++ main.cpp GeneratePrimeNumbers.cpp -o GeneratePrimeNumbers -std=c++20

unit_test:
	g++ ./Unit/GeneratePrimeNumbersTest.cpp GeneratePrimeNumbers.cpp -o GeneratePrimeNumbers_unit_tests -std=c++20
	./GeneratePrimeNumbers_unit_tests

# test: make
# 	chmod +x ./tests/testHtmlDecoderWithArgs.bash
# 	./tests/testHtmlDecoderWithArgs.bash
